// <auto-generated />
using AttendenceImport.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AttendenceImport.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201117073048_UpdateModel")]
    partial class UpdateModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AttendenceImport.Models.ExcelData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Attendance1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance10")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance11")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance12")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance13")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance14")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance15")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance16")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance17")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance18")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance19")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance20")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance21")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance22")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance23")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance24")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance25")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance26")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance27")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance28")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance29")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance30")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance31")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance32")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance33")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance34")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance35")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance36")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance37")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance38")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance39")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance40")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance41")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance42")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance43")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance44")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance45")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance46")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance47")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance48")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance49")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance5")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance50")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance51")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance52")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance53")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance54")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance55")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance56")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance6")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance7")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance8")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Attendance9")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AttendanceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("L1")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L10")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L11")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L12")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L13")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L14")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L15")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L16")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L17")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L18")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L19")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L2")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L20")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L21")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L22")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L23")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L24")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L25")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L26")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L27")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L28")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L29")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L3")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L30")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L31")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L32")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L33")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L34")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L35")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L36")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L37")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L38")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L39")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L4")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L40")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L41")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L42")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L43")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L44")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L45")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L46")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L47")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L48")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L49")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L5")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L50")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L51")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L52")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L53")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L54")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L55")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L56")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L6")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L7")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L8")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("L9")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Programme")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("ExcelData");
                });
#pragma warning restore 612, 618
        }
    }
}
