using Microsoft.EntityFrameworkCore.Migrations;

namespace AttendenceImport.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ExcelData",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StudentName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StudentID = table.Column<int>(type: "int", nullable: false),
                    Programme = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClassCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    StudentStatus = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    AttendanceStatus = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    L1 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance1 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L2 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance2 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L3 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance3 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L4 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance4 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L5 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance5 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L6 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance6 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L7 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance7 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L8 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance8 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L9 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance9 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L10 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance10 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L11 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance11 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L12 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance12 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L13 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance13 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L14 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance14 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L15 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance15 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L16 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance16 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L17 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance17 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L18 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance18 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L19 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance19 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L20 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance20 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L21 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance21 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L22 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance22 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L23 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance23 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L24 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance24 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L25 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance25 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L26 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance26 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L27 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance27 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L28 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance28 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L29 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance29 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L30 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance30 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L31 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance31 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L32 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance32 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L33 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance33 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L34 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance34 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L35 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance35 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L36 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance36 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L37 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance37 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L38 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance38 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L39 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance39 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L40 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance40 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L41 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance41 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L42 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance42 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L43 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance43 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L44 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance44 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L45 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance45 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L46 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance46 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L47 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance47 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L48 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance48 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L49 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance49 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L50 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance50 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L51 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance51 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L52 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance52 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L53 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance53 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L54 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance54 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L55 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance55 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    L56 = table.Column<string>(type: "nvarchar(1)", nullable: true),
                    Attendance56 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ExcelData", x => x.ID);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ExcelData");
        }
    }
}
